"""Generate supabase/seed.sql from the curated JSON catalog.

Usage (from backend/):  python -m scripts.generate_seed

The output is idempotent (INSERT ... ON CONFLICT DO UPDATE) so it can be re-run
against an existing database after catalog edits. Rows removed from the catalog
are deleted for catalog tables that learner data does not depend on.
"""
from __future__ import annotations

import json
from pathlib import Path

from ml.catalog import load_catalog

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "supabase" / "seed.sql"


def lit(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def arr(values, cast: str = "text[]") -> str:
    if not values:
        return f"'{{}}'::{cast}"
    return "array[" + ", ".join(lit(v) for v in values) + f"]::{cast}"


def main() -> None:
    c = load_catalog()
    out: list[str] = [
        "-- AUTO-GENERATED by backend/scripts/generate_seed.py from backend/ml/catalog_data/*.json",
        f"-- Catalog fingerprint: {c.fingerprint}. Do not edit by hand; edit the JSON and regenerate.",
        "begin;",
        "",
        "-- Topics",
    ]
    for t in c.topics.values():
        out.append(
            "insert into public.topics (id, name, domain, description, est_hours) values "
            f"({lit(t.id)}, {lit(t.name)}, {lit(t.domain)}, {lit(t.description)}, {t.est_hours}) "
            "on conflict (id) do update set name = excluded.name, domain = excluded.domain, "
            "description = excluded.description, est_hours = excluded.est_hours;"
        )

    out += ["", "-- Prerequisite edges (fully replaced)", "delete from public.topic_prerequisites;"]
    for t in c.topics.values():
        for p in t.prerequisites:
            out.append(f"insert into public.topic_prerequisites (topic_id, prerequisite_id) values ({lit(t.id)}, {lit(p)});")

    out += ["", "-- Careers"]
    for car in c.careers.values():
        out.append(
            "insert into public.careers (id, title, icon, description) values "
            f"({lit(car.id)}, {lit(car.title)}, {lit(car.icon)}, {lit(car.description)}) "
            "on conflict (id) do update set title = excluded.title, icon = excluded.icon, description = excluded.description;"
        )
    out += ["", "-- Career topic weights (fully replaced)", "delete from public.career_topics;"]
    for car in c.careers.values():
        for tid, w in car.topics.items():
            out.append(f"insert into public.career_topics (career_id, topic_id, weight) values ({lit(car.id)}, {lit(tid)}, {w});")

    out += ["", "-- Resources"]
    for r in c.resources.values():
        out.append(
            "insert into public.resources (id, topic_id, title, provider, instructor, url, format, difficulty, est_minutes, cost, "
            "description, tags) values "
            f"({lit(r.id)}, {lit(r.topic)}, {lit(r.title)}, {lit(r.provider)}, {lit(r.instructor) if r.instructor else 'null'}, "
            f"{lit(r.url)}, {lit(r.format)}, {lit(r.difficulty)}, {r.minutes}, {lit(r.cost)}, {lit(r.description)}, {arr(r.tags)}) "
            "on conflict (id) do update set topic_id = excluded.topic_id, title = excluded.title, provider = excluded.provider, "
            "instructor = excluded.instructor, url = excluded.url, format = excluded.format, difficulty = excluded.difficulty, "
            "est_minutes = excluded.est_minutes, cost = excluded.cost, description = excluded.description, tags = excluded.tags;"
        )

    out += ["", "-- Questions (answer keys: server-only table)"]
    for q in c.questions.values():
        out.append(
            "insert into public.questions (id, topic_id, difficulty, prompt, options, correct_index, explanation, expected_seconds) values "
            f"({lit(q.id)}, {lit(q.topic)}, {lit(q.difficulty)}, {lit(q.prompt)}, {lit(json.dumps(list(q.options), ensure_ascii=False))}::jsonb, "
            f"{q.correct_index}, {lit(q.explanation)}, {q.expected_seconds}) "
            "on conflict (id) do update set topic_id = excluded.topic_id, difficulty = excluded.difficulty, prompt = excluded.prompt, "
            "options = excluded.options, correct_index = excluded.correct_index, explanation = excluded.explanation, "
            "expected_seconds = excluded.expected_seconds;"
        )

    out += ["", "commit;", ""]
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(c.topics)} topics, {len(c.careers)} careers, "
          f"{len(c.resources)} resources, {len(c.questions)} questions")


if __name__ == "__main__":
    main()
