// End-to-end browser test: sign up → onboarding → diagnostics (weak, strong, rapid) → roadmap,
// recommendations, analytics and model evaluation. Fails (exit 1) on page errors, failed API calls
// or broken flows, and writes screenshots to e2e/shots/.
//
//   BASE_URL=http://localhost:3000 CHROME_PATH=/path/to/chrome node flow.mjs
// Without CHROME_PATH it uses the Chromium bundled with @sparticuz/chromium (Linux x64).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import puppeteer from "puppeteer-core";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const BASE = process.env.BASE_URL ?? "http://localhost:3000";
const OUT = path.join(HERE, "shots");
fs.mkdirSync(OUT, { recursive: true });
// Generated by `python -m scripts.export_e2e_answers` (backend/). Gitignored: it's the answer key.
const answers = JSON.parse(fs.readFileSync(path.join(HERE, ".answers.json"), "utf8"));
const problems = [];

async function launch() {
  if (process.env.CHROME_PATH) return puppeteer.launch({ executablePath: process.env.CHROME_PATH, headless: true, args: process.getuid?.() === 0 ? ["--no-sandbox"] : [] });
  const { default: chromium } = await import("@sparticuz/chromium");
  return puppeteer.launch({ executablePath: await chromium.executablePath(), args: chromium.args, headless: true });
}
const browser = await launch();
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 1 });
page.on("console", (m) => { if (m.type() === "error") problems.push(`console: ${m.text()}`); });
page.on("pageerror", (e) => problems.push(`pageerror: ${e.message}`));
page.on("requestfailed", (r) => problems.push(`requestfailed: ${r.url()} ${r.failure()?.errorText}`));
page.on("response", (r) => { if (r.status() >= 400 && !r.url().includes("_next")) problems.push(`http ${r.status()}: ${r.request().method()} ${r.url()}`); });

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const shot = async (name, full = true) => { await sleep(600); await page.screenshot({ path: `${OUT}/${name}.png`, fullPage: full }); console.log("shot", name); };
const clickText = async (text, sel = "button, a") => {
  const ok = await page.evaluate((t, s) => {
    const el = [...document.querySelectorAll(s)].find((e) => e.textContent.trim().includes(t) && !e.disabled);
    if (el) { el.click(); return true; } return false;
  }, text, sel);
  if (!ok) throw new Error(`No clickable element with text: ${text}`);
};
const waitText = (t, timeout = 15000) => page.waitForFunction((x) => document.body.innerText.includes(x), { timeout }, t);

async function answerAssessment(mode) {
  for (let i = 0; i < 5; i++) {
    await page.waitForSelector('[role="radiogroup"][aria-label="Answer options"]');
    await sleep(mode === "rapid" ? 250 : 3300);
    const prompt = await page.$eval("h1", (h) => h.textContent);
    const correct = answers[prompt];
    await page.evaluate((correct, mode) => {
      const opts = [...document.querySelectorAll('[aria-label="Answer options"] [role="radio"]')];
      const right = opts.find((o) => o.textContent.slice(1).trim() === correct);
      const pick = mode === "weak" ? opts.find((o) => o !== right) : right;
      pick.click();
    }, correct, mode);
    await clickText(mode === "weak" ? "Guessing" : "Sure", '[role="radio"]');
    await sleep(150);
    if (i < 4) await clickText("Next"); else await clickText("See my result");
  }
  await waitText(mode === "rapid" ? "Too fast to count" : "Level probabilities", 20000);
}

try {
  await page.goto(BASE, { waitUntil: "networkidle0" });
  await shot("01-landing");

  await page.goto(`${BASE}/signup`, { waitUntil: "networkidle0" });
  await page.type('input[autocomplete="name"]', "Maya Iyer");
  await page.type('input[type="email"]', `maya+${Date.now()}@example.com`);
  await page.type('input[type="password"]', "correct-horse-battery");
  await clickText("Create account");
  await page.waitForFunction(() => location.pathname === "/onboarding", { timeout: 15000 });
  await waitText("Where are you headed?");
  await shot("02-onboarding");

  await clickText("Data Analyst", '[role="radio"]');
  await clickText("Interactive", "button");
  await clickText("Video", "button");
  await page.type("textarea", "Build dashboards and answer product questions with SQL");
  await clickText("Build my roadmap");
  await page.waitForFunction(() => location.pathname === "/dashboard", { timeout: 15000 });
  await waitText("Up next");
  await shot("03-dashboard-new");

  // Weak first diagnostic on the first stop
  const firstStop = await page.$eval("ol li h3", (h) => h.textContent);
  console.log("first stop:", firstStop);
  await clickText("Test me");
  await page.waitForFunction(() => location.pathname.startsWith("/assessments/"), { timeout: 15000 });
  await shot("04-assessment-question", false);
  await answerAssessment("weak");
  await shot("05-result-weak");

  // Strong retake of the same topic
  await page.goto(`${BASE}/assessments`, { waitUntil: "networkidle0" });
  await waitText("History");
  await page.evaluate((name) => {
    const li = [...document.querySelectorAll("li")].find((l) => l.querySelector("h3")?.textContent === name);
    [...li.querySelectorAll("button")].find((b) => b.textContent.includes("Retest")).click();
  }, firstStop);
  await page.waitForFunction(() => /\/assessments\/[0-9a-f-]{36}/.test(location.pathname), { timeout: 15000 });
  await answerAssessment("strong");
  await shot("06-result-strong");
  console.log("adaptation:", await page.evaluate(() => [...document.querySelectorAll("h2")].find((h) => h.textContent === "What’s next" || h.textContent === "What's next")?.nextElementSibling?.textContent));

  // Also assess SQL strongly to unlock Advanced SQL
  await page.goto(`${BASE}/assessments`, { waitUntil: "networkidle0" });
  await page.evaluate(() => {
    const li = [...document.querySelectorAll("li")].find((l) => l.querySelector("h3")?.textContent === "SQL Fundamentals");
    li.querySelector("button").click();
  });
  await page.waitForFunction(() => /\/assessments\/[0-9a-f-]{36}/.test(location.pathname), { timeout: 15000 });
  await answerAssessment("strong");

  // Rapid click-through attempt must be stored but not counted
  await page.goto(`${BASE}/assessments`, { waitUntil: "networkidle0" });
  await page.evaluate(() => {
    const li = [...document.querySelectorAll("li")].find((l) => l.querySelector("h3")?.textContent === "Statistics Foundations");
    li.querySelector("button").click();
  });
  await page.waitForFunction(() => /\/assessments\/[0-9a-f-]{36}/.test(location.pathname), { timeout: 15000 });
  await answerAssessment("rapid");
  await shot("06b-not-counted", false);

  await page.goto(`${BASE}/dashboard`, { waitUntil: "networkidle0" });
  await waitText("Skill profile");
  await shot("07-dashboard-after");

  await page.goto(`${BASE}/roadmap`, { waitUntil: "networkidle0" });
  await page.waitForSelector(".react-flow__node");
  await shot("08-roadmap-graph", false);
  await clickText("Timeline", '[role="tab"]');
  await shot("09-roadmap-timeline");

  await page.goto(`${BASE}/recommendations`, { waitUntil: "networkidle0" });
  await waitText("Courses for you");
  await shot("10-recommendations");
  // "Start course" opens the provider in a new tab and marks the course in progress.
  const popup = new Promise((r) => browser.once("targetcreated", (t) => r(t)));
  await clickText("Start course", "a");
  const tab = await (await popup).page();
  await tab?.close();
  await page.bringToFront();
  await sleep(1500);
  await clickText("Done", "button");
  await sleep(1500);

  await page.goto(`${BASE}/recommendations?topic=advanced-sql`, { waitUntil: "networkidle0" });
  await waitText("Advanced SQL & Query Tuning");

  await page.goto(`${BASE}/analytics`, { waitUntil: "networkidle0" });
  await waitText("Accuracy by topic and difficulty");
  await shot("11-analytics");

  await page.goto(`${BASE}/ml`, { waitUntil: "networkidle0" });
  await waitText("Held-out test results");
  await shot("12-ml");

  await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2 });
  await page.goto(`${BASE}/dashboard`, { waitUntil: "networkidle0" });
  await waitText("Up next");
  await shot("13-mobile-dashboard");
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  if (overflow) problems.push("mobile: horizontal overflow on /dashboard");
} catch (e) {
  problems.push(`FLOW ERROR: ${e.message}`);
  await page.screenshot({ path: `${OUT}/error.png`, fullPage: true });
} finally {
  // An aborted RSC prefetch just means the test navigated away before it finished.
  // Provider favicons come from an external icon service, unreachable from sandboxed test machines.
  const real = [...new Set(problems)].filter((p) => !(p.startsWith("requestfailed") && p.includes("_rsc=") && p.includes("ERR_ABORTED"))
    && !p.includes("icons.duckduckgo.com") && !(p.startsWith("console: Failed to load resource") && p.includes("net::ERR_")));
  console.log("\nProblems:", real.length ? "\n  " + real.join("\n  ") : "none");
  await browser.close();
  process.exitCode = real.length ? 1 : 0;
}
